name: empowerher
description: AI-Powered Upskilling & Employment Platform for Underprivileged Women
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'  # Using the more specific SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Kept the higher version
  percent_indicator: ^4.2.3  # For progress bars
  intl: ^0.18.1  # For localization
  image_picker: any  # Added for new skill extraction feature
  # Add any other existing dependencies here
  dotted_border: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Kept the newer lint version

flutter:
  uses-material-design: true
  assets:
    - assets/
  # Uncomment if using custom fonts:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf